// <auto-generated />
namespace Project04_EntityFrameworkCodeFirstMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class remove_extra_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_extra_column));
        
        string IMigrationMetadata.Id
        {
            get { return "202607281233088_remove_extra_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
